server:
  port: 5000
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
spring:
  application:
    name: crow-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 114.132.251.6
    jedis:
      pool:
        max-idle: 100
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

aliyun:
  oss:
    accessKeySecret: qDFYomOzkzO6L9LAlFtK0xgo5RAl3T
    accessKeyId: LTAI4GGcB8CgTQZNjzffvm4M
    bucketDomain: http://cjcfirstbucket.oss-cn-guangzhou.aliyuncs.com
    bucketName: cjcfirstbucket
    endpoint: http://oss-cn-guangzhou.aliyuncs.com