server:
  port: 3000

spring:
  redis:
    host: 114.132.251.6


  application:
    name: crow-redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长