server:
  port: 80
spring:
  application:
    name: cjc-crowd-zuul
  redis:
    host: *
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*"
  sensitive-headers: "*"  # zuul重定向时保留头信息
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    crowd-portal:
      service-id: cjc-crowd-authentication
      path: /**
    crowd-project:
      service-id: cjc-crowd-project
      path: /project/**
  max:
    host:
      connections: 500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms[默认是1秒]
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  eureka:
    enabled: true