
spring:
  redis:
    host: 114.132.251.6
    port: 6379
  application:
    name: cjc-crowd-redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
server:
  port: 3000


