server:
  port: 4000
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: crow-authenticate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 114.132.251.6
    jedis:
      pool:
        max-idle: 100
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

short:
  message:
    appcode: 1be445bc362045bc96233015517f1109
    host: http://dingxin.market.alicloudapi.com
    path: /dx/sendSms
    method: post
    tpl-id: TP1711063

logging:
  level:
    com.cjc.crow.handler.MemberHandler: debug

ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长